name: Benchmark

on:
  pull_request:
    branches:
      - main
      - version*

jobs:
  benchmark:
    name: Benchmark

    permissions:
      pull-requests: write
      contents: write

    timeout-minutes: 1200
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: ["18.x", "20.x", "22.x"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v${{ matrix.node }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install

      - name: Print
        uses: ROBOTofficial/print@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          output-file: ./benchmark.log
          run: npm run benchmark
