name: Benchmark

on:
  pull_request:
    branches:
      - main
      - version*

jobs:
  benchmark:
    timeout-minutes: 1200
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x", "20.x", "22.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v${{ matrix.node }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - run: npm install
      - run: npm run build
      - run: npm run benchmark
