name: CI

on:
  pull_request:
    branches:
      - main
      - version*

jobs:
  ci:
    timeout-minutes: 600
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["18.x", "20.x", "22.x"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (v${{ matrix.node }})
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - run: bun install
      - run: npm run build
      - run: npm run lint
      - run: npm run check
      - run: npm test
